server: 
  port: 8761
  
spring:
 application:
    name: discovery-server
    

eureka:
  server:
    peer-node-read-timeout-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false